version: "3.7"
services:
  pg:
    image: postgres
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: postgres
    ports: 
      - 5432:5432
volumes:
  pg_data: